[pytest]
testpaths = tests
python_files = test_*.py *_test.py
pythonpath = .
addopts =
    -ra
    -v
    --strict-config
    --strict-markers
    -n auto
    --cov=src
    --cov=scripts
    --cov=utils
    --cov-report=term-missing
    --cov-report=html
    --cov-report=xml
